extends Node

signal damage_player(damage, attacker_position)
signal damage_baddie
signal player_kill
signal emit_player_global_position(player_position)
signal get_player_global_position
signal emit_player_global_position_drop(player_position)
signal get_player_global_position_drop
signal shoot_player

